#ifndef __CAN_RMP_H
#define __CAN_RMP_H

#include "stdint.h"
#include "can_packet.h"

// #define PROTNO_RMP 0x060 // Rectifier Monitor Protocol 监控模块与整流模块协议

// RMP 协议
#define VALUETYPE_RMP_GET_MOD_VOLTAGE 0x0001
#define VALUETYPE_RMP_GET_MOD_CURRENT_REAL 0x0002
#define VALUETYPE_RMP_GET_LIMIT_CURRENT_POINT 0x0003
#define VALUETYPE_RMP_GET_TEMP_M1 0x0004
#define VALUETYPE_RMP_GET_AC_VOLTAGE_COMPOSITE 0x0005
#define VALUETYPE_RMP_GET_VOLTAGE_UPPER_LIMIT 0x0006
#define VALUETYPE_RMP_GET_CURRENT_DISPLAY 0x0007
#define VALUETYPE_RMP_GET_PFC0_VOLTAGE 0x0008
#define VALUETYPE_RMP_GET_OVER_TEMP_POINT 0x0009
#define VALUETYPE_RMP_GET_PFC1_VOLTAGE 0x000A
#define VALUETYPE_RMP_GET_U1_BOARD_TEMP 0x000B
#define VALUETYPE_RMP_GET_AC_PHASE_A_VOLTAGE 0x000C
#define VALUETYPE_RMP_GET_AC_PHASE_B_VOLTAGE 0x000D
#define VALUETYPE_RMP_GET_AC_PHASE_C_VOLTAGE 0x000E
#define VALUETYPE_RMP_GET_DEFAULT_OUTPUT_VOLTAGE 0x000F
#define VALUETYPE_RMP_GET_PFC_TEMP 0x0010
#define VALUETYPE_RMP_GET_RATED_POWER 0x0011
#define VALUETYPE_RMP_GET_RATED_CURRENT 0x0012
#define VALUETYPE_RMP_GET_RATED_INPUT_VOLTAGE 0x0013
#define VALUETYPE_RMP_GET_POWER_LIMIT_POINT 0x0014
#define VALUETYPE_RMP_SET_DEFAULT_POWER_LIMIT 0x0018
#define VALUETYPE_RMP_SET_DEFAULT_CURRENT_LIMIT 0x0019
#define VALUETYPE_RMP_SET_AC_LIMIT_CURRENT 0x001A
#define VALUETYPE_RMP_SET_POWER_LIMIT 0x0020
#define VALUETYPE_RMP_SET_VOLTAGE 0x0021
#define VALUETYPE_RMP_SET_LIMIT_CURRENT_POINT 0x0022
#define VALUETYPE_RMP_SET_VOLTAGE_UPPER_LIMIT 0x0023
#define VALUETYPE_RMP_SET_DEFAULT_OUTPUT_VOLTAGE 0x0024
#define VALUETYPE_RMP_SET_OVER_TEMP_POINT 0x0025
#define VALUETYPE_RMP_SET_CURRENT_SHARE_VOLTAGE_ADJUST 0x0026
#define VALUETYPE_RMP_SET_PFC_OUTPUT_VOLTAGE 0x0027
#define VALUETYPE_RMP_SET_OVP_RESTART_TIME 0x0028
#define VALUETYPE_RMP_SET_WALKIN_TIME 0x0029
#define VALUETYPE_RMP_SET_STARTUP_INTERVAL 0x002A
#define VALUETYPE_RMP_SET_CAN_BAUDRATE 0x002B
#define VALUETYPE_RMP_SET_POWER_ON_OFF 0x0030
#define VALUETYPE_RMP_SET_OVP_RESET 0x0031
#define VALUETYPE_RMP_SET_WALKIN_ENABLE 0x0032
#define VALUETYPE_RMP_SET_FAN_FULL_SPEED 0x0033
#define VALUETYPE_RMP_SET_LED_GREEN_FLASH 0x0034
#define VALUETYPE_RMP_SET_OVP_RELAY_TRIP 0x0035
#define VALUETYPE_RMP_SET_CAN_INIT_RESET 0x0036
#define VALUETYPE_RMP_SET_CALIBRATION_STATE 0x0037
#define VALUETYPE_RMP_SET_MODULE_VERSION 0x0038
#define VALUETYPE_RMP_SET_OVP_VERSION 0x0039
#define VALUETYPE_RMP_SET_OVP_RELAY_ENABLE 0x003A
#define VALUETYPE_RMP_SET_MEMORY_TEST 0x003B
#define VALUETYPE_RMP_SET_REASSIGN_ADDRESS 0x003C
#define VALUETYPE_RMP_SET_PHASE_LOSS_ACTION 0x003D
#define VALUETYPE_RMP_SET_OVP_ASSOCIATION_ENABLE 0x003E
#define VALUETYPE_RMP_SET_SELF_DIAGNOSE 0x003F
#define VALUETYPE_RMP_GET_CURRENT_ALARM_STATUS 0x0040
#define VALUETYPE_RMP_GET_ANALOG_ALARM 0x0041
#define VALUETYPE_RMP_GET_OTHER_ALARM_STATUS 0x0042
#define VALUETYPE_RMP_GET_CURRENT_SHARE_VOLTAGE_ADJUST 0x0050
#define VALUETYPE_RMP_GET_MODULE_FEATURE 0x0051
#define VALUETYPE_RMP_GET_FIRST_MAINTENANCE 0x0052
#define VALUETYPE_RMP_GET_SECOND_MAINTENANCE 0x0053
#define VALUETYPE_RMP_GET_SERIALNO_LOW 0x0054
#define VALUETYPE_RMP_GET_SERIALNO_HIGH 0x0055
#define VALUETYPE_RMP_GET_VERSION 0x0056
#define VALUETYPE_RMP_GET_TOTAL_RUNTIME 0x0058
#define VALUETYPE_RMP_GET_MAINTENANCE_COUNT 0x0059
#define VALUETYPE_RMP_GET_BARCODE1 0x005A
#define VALUETYPE_RMP_GET_BARCODE2 0x005B
#define VALUETYPE_RMP_GET_BARCODE3 0x005C
#define VALUETYPE_RMP_GET_BARCODE4 0x005D
#define VALUETYPE_RMP_GET_FAN_VERSION 0x005E
#define VALUETYPE_RMP_GET_OVP_VERSION 0x005F
#define VALUETYPE_RMP_SET_VOLTAGE_SAMPLE_CAL_A 0x0060
#define VALUETYPE_RMP_SET_VOLTAGE_SAMPLE_CAL_B 0x0061
#define VALUETYPE_RMP_SET_CURRENT_SAMPLE_CAL_A 0x0062
#define VALUETYPE_RMP_SET_CURRENT_SAMPLE_CAL_B 0x0063
#define VALUETYPE_RMP_SET_VOLTAGE_CTRL_CAL_A 0x0064
#define VALUETYPE_RMP_SET_VOLTAGE_CTRL_CAL_B 0x0065
#define VALUETYPE_RMP_SET_LIMIT_CURRENT_CAL_A 0x0066
#define VALUETYPE_RMP_SET_LIMIT_CURRENT_CAL_B 0x0067
#define VALUETYPE_RMP_SET_AC_VOLTAGE_A_CAL_A 0x0068
#define VALUETYPE_RMP_SET_AC_VOLTAGE_A_CAL_B 0x0069
#define VALUETYPE_RMP_SET_AC_VOLTAGE_B_CAL_A 0x006A
#define VALUETYPE_RMP_SET_AC_VOLTAGE_B_CAL_B 0x006B
#define VALUETYPE_RMP_SET_PFC_VOLTAGE_SAMPLE_CAL_A 0x006C
#define VALUETYPE_RMP_SET_PFC_VOLTAGE_CTRL_CAL_A 0x006D
#define VALUETYPE_RMP_SET_TEMP_SAMPLE_CAL 0x006E
#define VALUETYPE_RMP_SET_POWER_LIMIT_CAL_A 0x0070
#define VALUETYPE_RMP_SET_POWER_LIMIT_CAL_B 0x0071
#define VALUETYPE_RMP_SET_AC_VOLTAGE_C_CAL_A 0x0072
#define VALUETYPE_RMP_SET_AC_VOLTAGE_C_CAL_B 0x0073
#define VALUETYPE_RMP_SET_PFC_VOLTAGE_SAMPLE_CAL_B 0x0074
#define VALUETYPE_RMP_SET_PFC_VOLTAGE_CTRL_CAL_B 0x0075
#define VALUETYPE_RMP_SET_AC_INPUT_CURRENT_CTRL_CAL_A 0x0076
#define VALUETYPE_RMP_SET_AC_INPUT_CURRENT_CTRL_CAL_B 0x0077
#define VALUETYPE_RMP_SET_FAN_CTRL_CAL_A 0x0078
#define VALUETYPE_RMP_SET_FAN_CTRL_CAL_B 0x0079
#define VALUETYPE_RMP_SET_SERIALNO_LOW 0x00A0
#define VALUETYPE_RMP_SET_SERIALNO_HIGH 0x00A1
#define VALUETYPE_RMP_SET_VERSION 0x00A2
#define VALUETYPE_RMP_SET_TOTAL_RUNTIME 0x00A4
#define VALUETYPE_RMP_SET_MAINTENANCE_COUNT 0x00A5
#define VALUETYPE_RMP_SET_BARCODE1 0x00A6
#define VALUETYPE_RMP_SET_BARCODE2 0x00A7
#define VALUETYPE_RMP_SET_BARCODE3 0x00A8
#define VALUETYPE_RMP_SET_BARCODE4 0x00A9
#define VALUETYPE_RMP_SET_MODULE_FEATURE 0x00AA
#define VALUETYPE_RMP_SET_FIRST_MAINTENANCE 0x00AB
#define VALUETYPE_RMP_SET_SECOND_MAINTENANCE 0x00AC
#define VALUETYPE_RMP_DCDC_MEM_SINGLE_READ 0x00E0
#define VALUETYPE_RMP_DCDC_MEM_WRITE 0x00E1
#define VALUETYPE_RMP_DCDC_EEPROM_ADDR_WRITE 0x00E2
#define VALUETYPE_RMP_DCDC_EEPROM_DATA_WRITE 0x00E3
#define VALUETYPE_RMP_PFC_MEM_SINGLE_READ 0x00E4
#define VALUETYPE_RMP_PFC_MEM_WRITE 0x00E5
#define VALUETYPE_RMP_PFC_EEPROM_ADDR_WRITE 0x00E6
#define VALUETYPE_RMP_PFC_EEPROM_DATA_WRITE 0x00E7
#define VALUETYPE_RMP_DCDC_MEM_CONT_READ 0x00E8
#define VALUETYPE_RMP_PFC_MEM_CONT_READ 0x00E9
#define VALUETYPE_RMP_MODULE_RESET 0x00FC
#define VALUETYPE_RMP_GET_BOOTLOADER_VERSION 0x00FD
#define VALUETYPE_RMP_BOOTLOADER_DOWNLOAD_TRIGGER 0x00FE
#define VALUETYPE_RMP_BOOTLOADER_DOWNLOAD_OLD_TI 0x00FF

#pragma pack(1) // 1字节对齐，确保结构体按1字节对齐方式存储

// MSGTYPE_CMD0_SET_REQ 0x00 // 设置请求数据 - 综合命令0

typedef struct
{
    uint8_t ac_ovp_disable : 1;   // Bit0: 交流过压保护允许，1=禁止，0=允许
    uint8_t can_init_reset : 1;   // Bit1: CAN初始化，1=复位，0=正常
    uint8_t ovp_relay_trip : 1;   // Bit2: 过压脱离继电器动作，1=脱离，0=正常
    uint8_t led_green_flash : 1;  // Bit3: 模块通信绿灯闪烁，1=闪烁，0=正常
    uint8_t fan_full_speed : 1;   // Bit4: 模块风扇是否全速，1=全速，0=自动
    uint8_t walk_in_enable : 1;   // Bit5: 设置模块是否WALK-IN，1=使能，0=禁止
    uint8_t ovp_reset_enable : 1; // Bit6: 设置模块过压复位，1=复位，0=正常
    uint8_t mod_power_off : 1;    // Bit7: 设置模块开关机，1=关机，0=开机
} can_rmp_msgtype_cmd0_set_req_byte2_t;

typedef struct
{
    uint8_t current_share_voltage_adjust;
    // RMP Byte3: 均流微调电压设置，无符号字节型数据
    // 128表示不调整电压，增大/减小代表电压升高/降低，步进1为最小调节单位
} can_rmp_msgtype_cmd0_set_req_byte3_t;

// 4字节浮点时间值，使用union方便float与字节数组转换
typedef union
{
    float runtime_hours_float; // 浮点数，单位小时，IEEE 754 标准单精度浮点
} can_rmp_msgtype_cmd0_set_req_byte4_7_t;

#define CAN_RMP_MSGTYPE_CMD0_SET_REQ_REDATA {0x01, 0x02, 0x03, 0x04, 0x05, 0x7, 0x40, 0x54, 0x58}

// MSGTYPE_CMD1_SET_REQ 0x10 // 设置请求数据 - 综合命令1
typedef struct
{
    uint8_t phase_loss_trip : 1; // Bit0: 缺相动作（1=关机，0=半载）
    uint8_t reserved : 7;        // Bit1~7: 保留，未使用
} can_rmp_msgtype_cmd1_set_req_byte2_t;

typedef struct
{
    uint8_t rsvd[5]; // 保留字节，未使用
} can_rmp_msgtype_cmd1_set_req_byte3_7_t;

#define CAN_PACK_MSGTYPE_CMD1_SET_REQ_REDATA {0x0C, 0x0D, 0x0E, 0x40}

// MSGTYPE_CMD2_SET_REQ 0x20 // 设置请求数据 - 综合命令2
typedef struct
{
    uint8_t rsvd[6]; // 保留字节，未使用
} can_rmp_msgtype_cmd2_set_req_byte2_7_t;

#define CAN_PACK_MSGTYPE_CMD2_SET_REQ_REDATA {0x0F, 0x11, 0x12, 0x13, 0x51, 0x55, 0x56, 0x5A, 0x5B, 0x5C, 0x5D}

// MSGTYPE_BYTE_READ_REQ 0x01  // 请求字节数据 - 按字节读取数据
typedef struct
{
    uint16_t valuetype;
} can_rmp_msgtype_byte_read_req_byte2_3_t;

typedef struct
{
    can_packet_data_value_u value;
} can_rmp_msgtype_byte_read_req_byte4_7_t;

// MSGTYPE_BYTE_READ_RESP 0x41 // 应答请求 - 按字节读取数据

// MSGTYPE_BIT_READ_REQ 0x02  // 请求位数据 - 按位读取数据
// MSGTYPE_BIT_READ_RESP 0x42 // 应答请求 - 按位读取数据

// MSGTYPE_BYTE_WRITE_REQ 0x03  // 设置数据 - 按字节设置数据
// MSGTYPE_BYTE_WRITE_RESP 0x43 // 应答设置 - 按字节设置数据

#pragma pack() // 恢复默认对齐方式

// RMP分发接口
void can_comm_rmp_dispatch(const can_packet_t *packet);

#endif
