#ifndef __PLECS_H
#define __PLECS_H

typedef enum
{
    PLECS_INPUT_SIM_TIME,
    PLECS_INPUT_ILA,
    PLECS_INPUT_ILB,
    PLECS_INPUT_IHV,
    PLECS_INPUT_ILV,
    PLECS_INPUT_FVS48,
    PLECS_INPUT_RVS12,
    PLECS_INPUT_TEMP1,
    PLECS_INPUT_TEMP2,
    PLECS_INPUT_TEMP3,
    PLECS_INPUT_ACCVS,
    PLECS_INPUT_ADDRS,
    PLECS_INPUT_PG_EN,
    PLECS_INPUT_V_OUT_REF,
    PLECS_INPUT_I_IN_LMT,
    PLECS_INPUT_I_OUT_LMT,
    PLECS_INPUT_V_IN_LMT,
    PLECS_INPUT_PWR_ON,
    PLECS_INPUT_PWR_IN_LMT,
    PLECS_INPUT_PWR_OUT_LMT,
    PLECS_INPUT_OPEN_LOOP_GAIN,
    PLECS_INPUT_OPEN_LOOP_MODE,
    PLECS_INPUT_MAX,
} PLECS_INPUT_E;

typedef enum
{
    PLECS_OUTPUT_PWMA1_DUTY,
    PLECS_OUTPUT_PWMHA1_EN,
    PLECS_OUTPUT_PWMLA1_EN,
    PLECS_OUTPUT_PWMA2_DUTY,
    PLECS_OUTPUT_PWMHA2_EN,
    PLECS_OUTPUT_PWMLA2_EN,
    PLECS_OUTPUT_PWMB1_DUTY,
    PLECS_OUTPUT_PWMHB1_EN,
    PLECS_OUTPUT_PWMLB1_EN,
    PLECS_OUTPUT_PWMB2_DUTY,
    PLECS_OUTPUT_PWMHB2_EN,
    PLECS_OUTPUT_PWMLB2_EN,
    PLECS_OUTPUT_AUXOFF,
    PLECS_OUTPUT_RED,
    PLECS_OUTPUT_GREEN,
    PLECS_OUTPUT_BLED1,
    PLECS_OUTPUT_BLED2,
    PLECS_OUTPUT_LEDS,
    PLECS_OUTPUT_DB2,
    PLECS_OUTPUT_DB1,
    PLECS_OUTPUT_DA2,
    PLECS_OUTPUT_DA1,
    PLECS_OUTPUT_RE,
    PLECS_OUTPUT_MAX = 30,
} PLECS_OUTPUT_E;

#define PLECS_INPUT_NUM PLECS_INPUT_MAX
#define PLECS_OUTPUT_NUM PLECS_OUTPUT_MAX

float plecs_get_input(PLECS_INPUT_E num);

void plecs_set_output(PLECS_OUTPUT_E num, float val);

#endif
